              -- LIBRARY_MANAGEMENT SYSTEM


DROP DATABASE IF EXISTS LIBRARY_MANAGEMENT;
CREATE DATABASE LIBRARY_MANAGEMENT;
USE LIBRARY_MANAGEMENT;
CREATE TABLE LIBRARIAN (
LIBRARIAN_ID INT PRIMARY KEY,
NAME VARCHAR(40),
EMAIL VARCHAR(40) UNIQUE ,
PASSWORD VARCHAR(50)
);
INSERT INTO LIBRARIAN  VALUES
(1,'AYESHA','HELLO@GMAIL.COM','SSSS'),
(2,'ALEENA','HIMSELF@GMAIL.COM','WWW');
SELECT*FROM LIBRARIAN;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
BOOK_ID INT PRIMARY KEY,
TITLE VARCHAR(40),
AUTHOR VARCHAR(40),
CATEGORY VARCHAR(40) ,
PUBLISHED_YEAR INT,
AVAILABLE_COPIES INT
);

INSERT INTO BOOKS VALUES
(101,'THE JAVA CORE','SHIFA','PROGRAMMING',2026,5),
(102,'THE C++ CORE','SANIA','DATABASE',2025,3),
(103,'THE PYTHON CORE','AHMED','SQL',2026,5);
SELECT*FROM BOOKS;
 CREATE TABLE MEMBERS (
 MEMBER_ID INT PRIMARY KEY,
 NAME VARCHAR(40),
 EMAIL VARCHAR(40) UNIQUE,
 ADDRESS VARCHAR(100)
 );
 INSERT INTO MEMBERS VALUES 
 (1,'SHIFA','SHIFA3.4@GMAIL.COM','WORKSHOP ROAD'),
(2,'AQSA','AQSA@GMAIL.COM','MILITARY ROAD'),
(3,'RIFFAT','RIFFAT@GMAIL.COM','HIRA HOSPITAL');
SELECT*FROM MEMBERS;

CREATE TABLE ISSUE_BOOK (
ISSUE_ID INT PRIMARY KEY,
MEMBER_ID INT ,
BOOK_ID INT ,
ISSUE_DATE DATE,
RETURN_DATE date,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
FOREIGN KEY (BOOK_ID) REFERENCES   BOOKS(BOOK_ID)
);
INSERT INTO ISSUE_BOOK VALUES
(1,1,101,'2026-07-10','2026-7-20'),
(2,2,102,'2026-07-12','2026-7-22'),
(3,3,103,'2026-07-15','2026-7-25');
SELECT * FROM LIBRARIAN;
SELECT*FROM MEMBERS;
SELECT*FROM BOOKS;
SELECT*FROM ISSUE_BOOK;
SELECT NAME FROM MEMBERS;
SELECT NAME,EMAIL FROM MEMBERS;
SELECT*FROM MEMBERS 
WHERE MEMBER_ID=2;
SELECT*FROM BOOKS
WHERE BOOK_ID=102;

SELECT*FROM issue_book
WHERE ISSUE_ID =3;

SELECT*FROM BOOKS
WHERE TITLE = 'THE JAVA CORE';

SELECT*FROM BOOKS
WHERE BOOK_ID>102;

SELECT*FROM BOOKS
WHERE BOOK_ID<102;

SELECT*FROM BOOKS
WHERE BOOK_ID>=102;

select*from members
WHERE MEMBER_ID !=1;

select*from members
WHERE MEMBER_ID=1 AND NAME='SHIFA';

SELECT*FROM MEMBERS
WHERE MEMBER_ID=1 OR MEMBER_ID=4;

SELECT * FROM MEMBERS
WHERE MEMBER_ID != 2;

SELECT*FROM MEMBERS 
ORDER BY MEMBER_ID ASC;

SELECT*FROM MEMBERS 
ORDER BY NAME ASC;


SELECT*FROM MEMBERS 
ORDER BY MEMBER_ID DESC;

SELECT COUNT(*)FROM MEMBERS;

SELECT COUNT(*)FROM BOOKS;
SELECT COUNT(*)FROM issue_book;

SELECT MAX(BOOK_ID)
FROM BOOKS;
SELECT MIN(BOOK_ID)
FROM BOOKS;

SELECT MIN(MEMBER_ID)
FROM MEMBERS;

SELECT MEMBERS.NAME, ISSUE_BOOK.ISSUE_DATE
FROM MEMBERS
INNER JOIN ISSUE_BOOK
ON MEMBERS.MEMBER_ID = ISSUE_BOOK.MEMBER_ID;

SELECT MEMBERS.NAME,
       BOOKS.TITLE,
       ISSUE_BOOK.ISSUE_DATE,
       ISSUE_BOOK.RETURN_DATE
FROM ISSUE_BOOK
INNER JOIN MEMBERS
ON ISSUE_BOOK.MEMBER_ID = MEMBERS.MEMBER_ID
INNER JOIN BOOKS
ON ISSUE_BOOK.BOOK_ID = BOOKS.BOOK_ID;

UPDATE MEMBERS
SET EMAIL = 'aqsa123@gmail.com'
WHERE MEMBER_ID = 2;
SELECT * FROM MEMBERS;

DELETE FROM MEMBERS
WHERE MEMBER_ID = 3;
SELECT*FROM members;


SELECT NAME
FROM MEMBERS
WHERE MEMBER_ID =
(
    SELECT MEMBER_ID
    FROM ISSUE_BOOK
    WHERE BOOK_ID = 101
);